const pilots = [
  { name: "Aya", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Aya.png" }, // Replace with actual image paths
  { name: "Belladonna", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Belladonna.png" },
  { name: "Cyrus", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Cyrus.png" },
  { name: "Fran", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Fran.png" },
  { name: "Furanku", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Furanku.png" },
  { name: "Iori", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Iori.png" },
  { name: "Ivan", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Ivan.png" },
  { name: "Jaka", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Jaka.png" },
  { name: "Jiu Chong", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Jiu Chong.png" },
  { name: "Joanna", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Joanna.png" },
  { name: "Kije", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Kije.png" },
  { name: "Kikina", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Kikina.png" },
  { name: "Kizuna Ai", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Kizuna Ai.png" },
  { name: "Lillian", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Lillian.png" },
  { name: "Lysa", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Lysa.png" },
  { name: "Matilda", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Matilda.png" },
  { name: "Mia", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Mia.png" },
  { name: "Mila", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Mila.png" },
  { name: "Mobius", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Mobius.png" },
  { name: "Nighthawk", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Nighthawk.png" },
  { name: "Ning", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Ning.png" },
  { name: "Norma", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Norma.png" },
  { name: "Opal", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Opal.png" },
  { name: "Purity", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Purity.png" },
  { name: "RED", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/RED.png" },
  { name: "Riko", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Riko.png" },
  { name: "Rom", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Rom.png" },
  { name: "Serena", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Serena.png" },
  { name: "Shin", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Shin.png" },
  { name: "Silver Deacon", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Silver Deacon.png" },
  { name: "Tarantula", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Tarantula.png" },
  { name: "Vanessa", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Vanessa.png" },
  { name: "Villar", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Villar.png" },
  { name: "Vita", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Vita.png" },
  { name: "Yang", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Yang.png" },
  { name: "Yulia", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Yulia.png" },
  { name: "Yutong", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Yutong.png" },
  { name: "Zoe", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/pilot/default/Zoe.png" }
  // ... more pilots
];