const pilots = [
  { name: "Aya", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Aya.png" }, // Replace with actual image paths
  { name: "Belladonna", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Belladonna.png" },
  { name: "Cyrus", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Cyrus.png" },
  { name: "Fran", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Fran.png" },
  { name: "Furanku", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Furanku.png" },
  { name: "Iori", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Iori.png" },
  { name: "Ivan", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Ivan.png" },
  { name: "Jaka", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Jaka.png" },
  { name: "Jiu Chong", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Jiu Chong.png" },
  { name: "Joanna", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Joanna.png" },
  { name: "Kije", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Kije.png" },
  { name: "Kikina", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Kikina.png" },
  { name: "Kizuna Ai", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Kizuna Ai.png" },
  { name: "Lillian", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Lillian.png" },
  { name: "Lysa", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Lysa.png" },
  { name: "Matilda", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Matilda.png" },
  { name: "Mia", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Mia.png" },
  { name: "Mila", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Mila.png" },
  { name: "Mobius", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Mobius.png" },
  { name: "Nighthawk", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Nighthawk.png" },
  { name: "Ning", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Ning.png" },
  { name: "Norma", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Norma.png" },
  { name: "Opal", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Opal.png" },
  { name: "Purity", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Purity.png" },
  { name: "RED", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/RED.png" },
  { name: "Riko", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Riko.png" },
  { name: "Rom", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Rom.png" },
  { name: "Serena", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Serena.png" },
  { name: "Shin", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Shin.png" },
  { name: "Silver Deacon", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Silver Deacon.png" },
  { name: "Tarantula", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Tarantula.png" },
  { name: "Vanessa", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Vanessa.png" },
  { name: "Villar", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Villar.png" },
  { name: "Vita", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Vita.png" },
  { name: "Yang", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Yang.png" },
  { name: "Yulia", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Yulia.png" },
  { name: "Yutong", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Yutong.png" },
  { name: "Zoe", rarity: "Default", image: "index_data/images/textures/cards/def_pilot/Zoe.png" }
  // ... more pilots
];