const mechas = [
  { name: "Akashic", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Akashic.png" }, // Replace with actual image paths
  { name: "Alborada", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Alborada.png" },
  { name: "Andromeda", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Andromeda.png" },
  { name: "Arthur", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Arthur.png" },
  { name: "Aurora", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Aurora.png" },
  { name: "Boltus", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Boltus.png" },
  { name: "Caramel", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Caramel.png" },
  { name: "Death Knell", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Death Knell.png" },
  { name: "Doomlight", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Doomlight.png" },
  { name: "Dreadwolf", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Dreadwolf.png" },
  { name: "Firefox", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Firefox.png" },
  { name: "Firestar", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Firestar.png" },
  { name: "Flamenco", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Flamenco.png" },
  { name: "Gabriel", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Gabriel.png" },
  { name: "Gaia", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Gaia.png" },
  { name: "Guerilla Hunter", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Guerilla Hunter.png" },
  { name: "Hotsteel", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Hotsteel.png" },
  { name: "Hurricane", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Hurricane.png" },
  { name: "JOJO", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Jojo.png" },
  { name: "Lancelot", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Lancelot.png" },
  { name: "Michael", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Michael.png" },
  { name: "Moon Rabbit", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Moon Rabbit.png" },
  { name: "Nebula", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Nebula.png" },
  { name: "Neutron Star", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Neutron Star.png" },
  { name: "Northern Knight", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Northern Knight.png" },
  { name: "Pulsar", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Pulsar.png" },
  { name: "Ranger", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Ranger.png" },
  { name: "Raven", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Raven.png" },
  { name: "Shiranui", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Shiranui.png" },
  { name: "Skyfall", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Skyfall.png" },
  { name: "Skyfire", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Skyfire.png" },
  { name: "Skylark", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Skylark.png" },
  { name: "Snow Mirage", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Snow Mirage.png" },
  { name: "Tempest", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Tempest.png" },
  { name: "Trio of Enders", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Trio of Enders.png" },
  { name: "Twilight", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Twilight.png" },
  { name: "Ventorus", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Ventorus.png" }
  // ... more mechas
];