const mechas = [
  { name: "Akashic", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Akashic.png" }, // Replace with actual image paths
  { name: "Alborada", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Alborada.png" },
  { name: "Andromeda", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Andromeda.png" },
  { name: "Arthur", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Arthur.png" },
  { name: "Aurora", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Aurora.png" },
  { name: "Boltus", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Boltus.png" },
  { name: "Caramel", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Caramel.png" },
  { name: "Death Knell", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Death Knell.png" },
  { name: "Doomlight", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Doomlight.png" },
  { name: "Dreadwolf", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Dreadwolf.png" },
  { name: "Firefox", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Firefox.png" },
  { name: "Firestar", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Firestar.png" },
  { name: "Flamenco", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Flamenco.png" },
  { name: "Gabriel", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Gabriel.png" },
  { name: "Gaia", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Gaia.png" },
  { name: "Guerilla Hunter", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Guerilla Hunter.png" },
  { name: "Hotsteel", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Hotsteel.png" },
  { name: "Hurricane", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Hurricane.png" },
  { name: "JOJO", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Jojo.png" },
  { name: "Lancelot", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Lancelot.png" },
  { name: "Michael", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Michael.png" },
  { name: "Moon Rabbit", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Moon Rabbit.png" },
  { name: "Nebula", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Nebula.png" },
  { name: "Neutron Star", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Neutron Star.png" },
  { name: "Northern Knight", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Northern Knight.png" },
  { name: "Pulsar", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Pulsar.png" },
  { name: "Ranger", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Ranger.png" },
  { name: "Raven", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Raven.png" },
  { name: "Shiranui", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Shiranui.png" },
  { name: "Skyfall", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Skyfall.png" },
  { name: "Skyfire", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Skyfire.png" },
  { name: "Skylark", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Skylark.png" },
  { name: "Snow Mirage", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Snow Mirage.png" },
  { name: "Tempest", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Tempest.png" },
  { name: "Trio of Enders", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Trio of Enders.png" },
  { name: "Twilight", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Twilight.png" },
  { name: "Ventorus", rarity: "Default", image: "index_data/plugins/lucky_house/Index_data/textures/cards/mecha/default/Ventorus.png" }
  // ... more mechas
];