function languagesContents() {
  var a000 = document.getElementById("SettingsTitleLang");
  var a001 = document.getElementById("aboutTab");
  var a002 = document.getElementById("systemTab");
  var a003 = document.getElementById("snakeTab");
  var a004 = document.getElementById("foodTab");
  var a005 = document.getElementById("boardTab");
  var a006 = document.getElementById("audioTab");
  var a007 = document.getElementById("difficultyLang");
  var a008 = document.getElementById("normalDif");
  var a009 = document.getElementById("hardDif");
  var a010 = document.getElementById("hellDif");
  var a011 = document.getElementById("langsLangs");
  var a012 = document.getElementById("boardMapAlphaLang");
  var a013 = document.getElementById("boardMapOrigoLang");
  var a014 = document.getElementById("gameTab");
  var a015 = document.getElementById("uploadDataLang");
  var a016 = document.getElementById("saveProgDataViafile");
  var a017 = document.getElementById("meowLang");
  var a018 = document.getElementById("goldLang");
  var a019 = document.getElementById("alphaLang");
  var a020 = document.getElementById("crystalLang");
  var a021 = document.getElementById("ticketLang");
  var a022 = document.getElementById("cTicketLang");
  var a023 = document.getElementById("pTicketLang");
  var a024 = document.getElementById("muteLang");
  var a025 = document.getElementById("sfxLang");
  var a026 = document.getElementById("netEaseLang1");
  var a027 = document.getElementById("netEaseLang2");
  var a028 = document.getElementById("coderLang");
  var a029 = document.getElementById("baseCodeLang");
  var a030 = document.getElementById("getscore");
  var a031 = document.getElementById("loseText");
  var a032 = document.getElementById("defaultSettings");
  var a033 = document.getElementById("applySettings");
  var a034 = document.getElementById("controllerSettingsLangs");
  var a035 = document.getElementById("cspLang");
  var a036 = document.getElementById("ccLang");
  var a037 = document.getElementById("clLang");
  var a038 = document.getElementById("crLang");
  var a039 = document.getElementById("noticeTitleLang");
  var a040 = document.getElementById("f12ToolLang");
  var a041 = document.getElementById("musicLang");
  var a042 = document.getElementById("musicstyleLang");
  var a043 = document.getElementById("navBtn");
  var a044 = document.getElementById("btn002");
  var a045 = document.getElementById("deleteprogbutton");
  var a046 = document.getElementById("langImportantLang");
  var a047 = document.getElementById("ifMobileLang");
//  var a048 = document.getElementById("");
  var a049 = document.getElementById("snakeTabsound");
  var a050 = document.getElementById("autoScoreLang");
  var a051 = document.getElementById("profileTitleLang");
  var a052 = document.getElementById("clickable0Lang");
  var a053 = document.getElementById("cratedOn0Lang");
  var a054 = document.getElementById("txtAhow");
  var a055 = document.getElementById("loadingText");
  var a056 = document.getElementById("loadClassic");
  var a057 = document.getElementById("randomSnakeLang");
  var a058 = document.getElementById("loadingLangStyle");
  var a059 = document.getElementById("boardMapAlpha2Lang");
  var a060 = document.getElementById("adminToolsLang");
  var a061 = document.getElementById("exitSiteLang");
  var a062 = document.getElementById("noticeUpLang");
  var a063 = document.getElementById("ambLang");
  var a064 = document.getElementById("howTitleLang");
  var a065 = document.getElementById("ifOthersLang");
  var a066 = document.getElementById("txtBhow");
  var a067 = document.getElementById("pTicket2Lang");
  var a068 = document.getElementById("virtualTokenLang");
  var a069 = document.getElementById("subButton");
  var a070 = document.getElementById("dataRunner");
  var a071 = document.getElementById("snakeColorLang");
  var a072 = document.getElementById("defOptionLang");
  var a073 = document.getElementById("dynOptionLang");
  var a074 = document.getElementById("swaOptionLang");
  var a075 = document.getElementById("servicesLang");
  var a076 = document.getElementById("displayFpsLang");
  var a077 = document.getElementById("xSnakeValueLang");
  var a078 = document.getElementById("ySnakeValueLang");
  const a000_all = document.getElementsByClassName('settingscontent');
  const a001_all = document.getElementsByClassName('stylescontent');
  const a002_all = document.getElementsByClassName('coming-soon');
  const a003_all = document.getElementsByClassName('moresettingscontent');
  const a004_all = document.getElementsByClassName('totopelement');
  const a005_all = document.getElementsByClassName('serviceLang');
  const a006_all = document.getElementsByClassName('r-stars');
  const a007_all = document.getElementsByClassName('r-star');
//  const a008_all = document.getElementsByClassName('');
  const a009_all = document.getElementsByClassName('label-range');
  const a010_all = document.getElementsByClassName('dlLabel');
  const a011_all = document.getElementsByClassName('lasbLang');
  if(localStorage.getItem("lang") === "en") {
    a000.innerHTML = "Settings";
    a001.innerHTML = "About";
    a002.innerHTML = "System";
    a003.innerHTML = "Snake";
    a004.innerHTML = "Food";
    a005.innerHTML = "Board";
    a006.innerHTML = "Audio";
    a007.innerHTML = "Difficulty:";
    a008.innerHTML = "Normal";
    a009.innerHTML = "Hard";
    a010.innerHTML = "Hell";
    a011.innerHTML = "Languages:";
    a012.innerHTML = "Alpha City Map";
    a013.innerHTML = "Origo Island Map";
    a014.innerHTML = "Game";
    a015.innerHTML = "Load data via file (.js)";
    a016.value = "Save data on file";
    a017.innerHTML = "Meow Token";
    a018.innerHTML = "Gold";
    a019.innerHTML = "Alpha Coin";
    a020.innerHTML = "Crystal";
    a021.innerHTML = "Ticket";
    a022.innerHTML = "Chromatic Ticket";
    a023.innerHTML = "Premium Ticket";
    a024.innerHTML = "Mute Audio";
    a025.innerHTML = "SFX Volume";
    a026.innerHTML = "Privacy Policy, Terms and Conditions";
    a027.innerHTML = "©1997-2025 NetEase, Inc.All Rights Reserved";
    a028.innerHTML = "Coding: " + "ArthurVesta;";
    a029.innerHTML = "Base Code: From";
    a030.innerHTML = "Score: 0";
    a031.innerHTML = "Game Over!";
    a032.value = "Default";
    a033.value = "Apply";
    a034.innerHTML = "Controller:";
    a035.innerHTML = "Position:";
    a036.innerHTML = "Center";
    a037.innerHTML = "Left";
    a038.innerHTML = "Right";
    a039.innerHTML = "Notice";
    a040.innerHTML = "Developer tools";
    a041.innerHTML = "Background Music";
    a042.innerHTML = "Music";
    a043.innerHTML = "MENU";
    a044.innerHTML = "MENU";
    a045.value = "Delete Progress";
    a046.innerHTML = "(Language translations may not be 100% accurate)";
    a047.innerHTML = "If users use Mobiles (Android, iPhone, iPad, Tablets)";
//    a048.innerHTML = "";
    a049.innerHTML = "Snake";
    a050.innerHTML = "Auto load the saved score";
    a051.innerHTML = "Collection Center";
    a052.innerHTML = "> Clickable <";
    a053.innerHTML = "Coded on: ";
    a054.innerHTML = "Can be selected 3 types of game controlling:<br>";
    a054.innerHTML += "(open menu/System)<br>";
    a054.innerHTML += "Classic.<br>";
    a054.innerHTML += "Dynamic.<br>";
    a054.innerHTML += "Touch.<br>";
    a054.innerHTML += "Classic: need press on buttons.<br>";
    a054.innerHTML += "Dynamic: need press on buttons but position of buttons changed.<br>";
    a054.innerHTML += "Touch: gestures on screen for change the side of snake.";
    if(localStorage.getItem("loadingStyle") === "anime") {
      a055.innerHTML = "";
    }else{
      a055.innerHTML = "Loading Assets…";
    }
    a056.innerHTML = "Classic";
    a057.innerHTML = "Snake position";
    a058.innerHTML = "Loading Animation";
    a059.innerHTML = "Alpha City Map 2";
    a060.innerHTML = "Developments";
    a061.innerHTML = "Exit";
    a062.innerHTML = "Notice";
    a063.innerHTML = "Ambient";
    a064.innerHTML = "How to play";
    a065.innerHTML = "If users use other devices (Windows, MacOS, Linux)";
    a066.innerHTML = "Keyboard keys:<br>";
    a066.innerHTML += "↑←↓→ and W.A.S.D: Start game.<br>";
    a066.innerHTML += "Space bar: Pause and continue game.<br>";
    a066.innerHTML += "ESC: Open/close menu.<br>";
    a066.innerHTML += "E: Open/close collection center.<br>";
    a066.innerHTML += "Enter: Continue if alert is open and close the ''Game Over'' Window.";
    a067.innerHTML = "Premium Ticket";
    a068.innerHTML = "Virtual Token";
    a069.value = "Upload(.js)";
    a070.value = "Load";
    a071.innerHTML = "Snake color";
    a072.innerHTML = "Classic controller";
    a073.innerHTML = "DYnamic controller";
    a074.innerHTML = "Touch Screen Gestures";
    a075.innerHTML = "Services";
    a076.innerHTML = "Show FPS (BETA)";
    a077.innerHTML = "Horizontally Snake Position";
    a078.innerHTML = "Vertically Snake Position";
    for (let i = 0; i < a000_all.length; i++) {
      a000_all[i].textContent = 'Settings:';
    };
    for (let i = 0; i < a001_all.length; i++) {
      a001_all[i].textContent = 'Style:';
    };
    for (let i = 0; i < a002_all.length; i++) {
      a002_all[i].textContent = 'Coming Soon!, Wait for updates.';
    };
    for (let i = 0; i < a003_all.length; i++) {
      a003_all[i].textContent = 'More:';
    };
    for (let i = 0; i < a004_all.length; i++) {
      a004_all[i].textContent = 'To start';
    };
    for (let i = 0; i < a005_all.length; i++) {
      a005_all[i].textContent = 'Services:';
    };
    for (let i = 0; i < a006_all.length; i++) {
      a006_all[i].classList.add("en");
    };
    for (let i = 0; i < a007_all.length; i++) {
      a007_all[i].classList.add("en");
    };
    for (let i = 0; i < a010_all.length; i++) {
      a010_all[i].textContent = 'Download';
    };
    for (let i = 0; i < a011_all.length; i++) {
      a011_all[i].textContent = 'Anime';
    };
    document.title = "Snake Mecha Collector";
  }else
  if(localStorage.getItem("lang") === "ru") {
    a000.innerHTML = "Настр'";
    a001.innerHTML = "О";
    a002.innerHTML = "Система";
    a003.innerHTML = "Змея";
    a004.innerHTML = "Еда";
    a005.innerHTML = "Доска";
    a006.innerHTML = "Аудио";
    a007.innerHTML = "Сложность:";
    a008.innerHTML = "Нормальный";
    a009.innerHTML = "Тяжелый";
    a010.innerHTML = "Адский";
    a011.innerHTML = "Языки:";
    a012.innerHTML = "Карта города Альфа";
    a013.innerHTML = "Карта острова Ориго";
    a014.innerHTML = "Игра";
    a015.innerHTML = "Загрузка данных через файл (.js)";
    a016.value = "Сохранить данные в файле";
    a017.innerHTML = "Мяу-жетон";
    a018.innerHTML = "Золото";
    a019.innerHTML = "Альфа-монета";
    a020.innerHTML = "Кристалл";
    a021.innerHTML = "Билет";
    a022.innerHTML = "Хроматический билет";
    a023.innerHTML = "Премиум-билет";
    a024.innerHTML = "Отключить звук";
    a025.innerHTML = "Громкость SFX";
    a026.innerHTML = "Политика конфиденциальности, положения и условия";
    a027.innerHTML = "©1997-2025 NetEase, Inc.Все права защищены";
    a028.innerHTML = "Кодирование: " + "ArthurVesta;";
    a029.innerHTML = "Базовый код: Из ";
    a030.innerHTML = "Счет: 0";
    a031.innerHTML = "Игра закончена!";
    a032.value = "По умолч";
    a033.value = "Применять";
    a034.innerHTML = "Контроллер:";
    a035.innerHTML = "Позиция:";
    a036.innerHTML = "Центрый";
    a037.innerHTML = "Левый";
    a038.innerHTML = "Правый";
    a039.innerHTML = "Уведомление";
    a040.innerHTML = "";
    a041.innerHTML = "Фоновая музыка";
    a042.innerHTML = "Музыка";
    a043.innerHTML = "МЕНЮ";
    a044.innerHTML = "МЕНЮ";
    a045.value = "Удалить Прогресс";
    a046.innerHTML = "(Переводы могут содержать ошибки)";
    a047.innerHTML = "Если пользователи используют мобильные (Android, iPhone, iPad, планшеты)";
//    a048.innerHTML = "";
    a049.innerHTML = "Змея";
    a050.innerHTML = "Автоматически загрузить сохраненного счета";
    a051.innerHTML = "Центр сбора";
    a052.innerHTML = "> Нажемной <";
    a053.innerHTML = "Кодировано на: ";
    a054.innerHTML = "Можно выбрать 3 типа управления игрой:<br>";
    a054.innerHTML += "(откройте меню/Система)<br>";
    a054.innerHTML += "Классический.<br>";
    a054.innerHTML += "Динамичный.<br>";
    a054.innerHTML += "Прикосновение.<br>";
    a054.innerHTML += "Классический: нужно нажать на кнопки.<br>";
    a054.innerHTML += "Динамичный: нужно нажать на кнопки, но положение кнопок изменилось.<br>";
    a054.innerHTML += "Прикосновение: жесты на экране для смены стороны змеи.";
    if(localStorage.getItem("loadingStyle") === "anime") {
      a055.innerHTML = "";
    }else{
      a055.innerHTML = "Загрузка Ресурсы…";
    }
    a056.innerHTML = "Классический";
    a057.innerHTML = "Положение змеи";
    a058.innerHTML = "Анимация загрузки";
    a059.innerHTML = "Карта города Альфа 2";
    a060.innerHTML = "Разработки";
    a061.innerHTML = "Выход";
    a062.innerHTML = "Уведом'";
    a063.innerHTML = "Окружение";
    a064.innerHTML = "Как играть";
    a065.innerHTML = "Если пользователи используют другие устройства (Windows, MacOS, Linux)";
    a066.innerHTML = "Клавиши клавиатура:<br>";
    a066.innerHTML += "↑←↓→ и Ц.Ф.Ы.В: Начать игру.<br>";
    a066.innerHTML += "Пробел: Пауза и продолжение игры.<br>";
    a066.innerHTML += "ESC: Открыть/закрыть меню.<br>";
    a066.innerHTML += "E: Открыть/закрыть центр сбора.<br>";
    a066.innerHTML += "Enter: Продолжить, если открыто оповещение, и закрыть окно «Игра окончена».";
    a067.innerHTML = "Премиум-билет";
    a068.innerHTML = "Виртуальный токен";
    a069.value = "Загрузить(.js)";
    a070.value = "Загрузить";
    a071.innerHTML = "Цвет змеи";
    a072.innerHTML = "Классический контроллер";
    a073.innerHTML = "Динамический контроллер";
    a074.innerHTML = "Жесты сенсорного экрана";
    a075.innerHTML = "Услуги";
    a076.innerHTML = "Показать FPS (БЕТА)";
    a077.innerHTML = "Горизонтальное положение змеи";
    a077.innerHTML = "Вертикальная положение змеи";
    for (let i = 0; i < a000_all.length; i++) {
      a000_all[i].textContent = 'Настройки:';
    };
    for (let i = 0; i < a001_all.length; i++) {
      a001_all[i].textContent = 'Стиль:';
    };
    for (let i = 0; i < a002_all.length; i++) {
      a002_all[i].textContent = 'Скоро!, Ждите обновлений.';
    };
    for (let i = 0; i < a003_all.length; i++) {
      a003_all[i].textContent = 'Более:';
    };
    for (let i = 0; i < a004_all.length; i++) {
      a004_all[i].textContent = 'К началу';
    };
    for (let i = 0; i < a005_all.length; i++) {
      a005_all[i].textContent = 'Услуги:';
    };
    for (let i = 0; i < a006_all.length; i++) {
      a006_all[i].classList.add("ru");
    };
    for (let i = 0; i < a007_all.length; i++) {
      a007_all[i].classList.add("ru");
    };
    for (let i = 0; i < a010_all.length; i++) {
      a010_all[i].textContent = 'Скачать';
    };
    for (let i = 0; i < a011_all.length; i++) {
      a011_all[i].textContent = 'Аниме';
    };
    document.title = "Змея Меха Сборщик";
  }else
  if(localStorage.getItem("lang") === "he") {
    a000.innerHTML = "הגדרות";
    a001.innerHTML = "אודות";
    a002.innerHTML = "מערכת";
    a003.innerHTML = "נחש";
    a004.innerHTML = "אוכל";
    a005.innerHTML = "לוח";
    a006.innerHTML = "אודיו";
    a007.innerHTML = "קושי:";
     a007.style.direction = "rtl";
     a007.style.textAlign = "right";
    a008.innerHTML = "רגיל";
    a009.innerHTML = "קשה";
    a010.innerHTML = "גהנום";
    a011.innerHTML = "שפות:";
     a011.style.direction = "rtl";
     a011.style.textAlign = "right";
    a012.innerHTML = "מפת עיר אלפא";
    a013.innerHTML = "מפת אי אוריגו";
    a014.innerHTML = "משחק";
    a015.innerHTML = "טעינת נתונים דרך קובץ (.js)";
     a015.style.direction = "rtl";
    a016.value = "שמירת נתונים בקובץ";
    a017.innerHTML = "מיאו אסימון";
    a018.innerHTML = "זהב";
    a019.innerHTML = "מתבעת אלפא";
    a020.innerHTML = "גביש";
    a021.innerHTML = "כרטיס";
    a022.innerHTML = "כרטיס כרומטי";
    a023.innerHTML = "כרטיס פרימיום";
    a024.innerHTML = "השתקת שמע";
     a024.style.width = "100%";
     a024.style.textAlign = "right";
    a025.innerHTML = "עוצמת SFX";
     a025.style.direction = "rtl";
     a025.style.textAlign = "right";
    a026.innerHTML = "מדיניות פרטיות, תנאים והגבלות";
    a027.innerHTML = "©1997-2025 NetEase, Inc. כל הזכויות שמורות";
     a027.style.direction = "rtl";
    a028.innerHTML = "קידוד: " + "ArthurVesta;";
     a028.style.direction = "rtl";
    a029.innerHTML = "קוד בסיס: מאת";
     a029.style.direction = "rtl";
    a030.innerHTML = "ניקוד: 0";
    a031.innerHTML = "משחק נגמר!";
     a031.style.direction = "rtl";
    a032.value = "ב''מחדל";
    a033.value = "החל";
    a034.innerHTML = "בקר:";
     a034.style.direction = "rtl";
     a034.style.textAlign = "right";
    a035.innerHTML = "מיקום:";
     a035.style.direction = "rtl";
     a035.style.textAlign = "right";
    a036.innerHTML = "מרכז";
    a037.innerHTML = "שמאל";
    a038.innerHTML = "ימין";
    a039.innerHTML = "הודעה";
     a039.style.textAlign = "right";
     a039.style.width = "75%";
    a040.innerHTML = "כלי פיתוח";
     a040.style.width = "100%";
     a040.style.textAlign = "right";
     a040.style.paddingRight = "45px";
    a041.innerHTML = "מוסיקת רקע";
     a041.style.width = "100%";
     a041.style.textAlign = "right";
    a042.innerHTML = "מוסיקה";
    a043.innerHTML = "תפריט";
    a044.innerHTML = "תפריט";
    a045.value = "מחיקת התקדמות";
    a046.innerHTML = "(ייתכן שתרגומי שפה לא יהיו מדויקים ב-100%)";
    a047.innerHTML = "אם משתמשים משתמשים בטלפונים ניידים (אנדרואיד, אייפון, אייפד, טאבלטים)";
     a047.style.textAlign = "right";
//    a048.innerHTML = "";
    a049.innerHTML = "נחש";
    a050.innerHTML = "טעינה אוטומטית של הציון הנשמר";
     a050.style.width = "100%";
     a050.style.textAlign = "right";
    a051.innerHTML = "מרכז איסוף";
     a051.style.textAlign = "right";
     a051.style.width = "75%";
    a052.innerHTML = "> נלחץ <";
    a053.innerHTML = "קודד על: ";
     a053.style.direction = "rtl";
    a054.innerHTML = "ניתן לבחור 3 סוגים של שליטה במשחק:<br>";
    a054.innerHTML += "(פתח תפריט/מערכת)<br>";
    a054.innerHTML += "קלאסי.<br>";
    a054.innerHTML += "דינמי.<br>";
    a054.innerHTML += "מגע.<br>";
    a054.innerHTML += "קלאסי: צריך ללחוץ על כפתורים.<br>";
    a054.innerHTML += "דינמי: צריך ללחוץ על הכפתורים אבל מיקום הכפתורים ישתנה.<br>";
    a054.innerHTML += "מגע: מחוות על המסך לשינוי צד של נחש.";
     a054.style.direction = "rtl";
     a054.style.textAlign = "right";
    if(localStorage.getItem("loadingStyle") === "anime") {
      a055.innerHTML = "";
    }else{
      a055.innerHTML = "טוען נכסים…";
    }
    a056.innerHTML = "קלאסי";
    a057.innerHTML = "תנוחה של הנחש";
     a057.style.direction = "rtl";
     a057.style.textAlign = "right";
    a058.innerHTML = "אנימציית טעינה";
    a059.innerHTML = "מפת עיר אלפא 2";
    a060.innerHTML = "התפתחויות";
     a060.style.width = "100%";
     a060.style.textAlign = "right";
    a061.innerHTML = "יציאה";
    a062.innerHTML = "הודעה";
    a063.innerHTML = "סביבה";
     a063.style.width = "100%";
     a063.style.textAlign = "right";
    a064.innerHTML = "איך לשחק";
     a064.style.textAlign = "right";
     a064.style.width = "75%";
    a065.innerHTML = "אם משתמשים משתמשים במחשירים אחרים (Windows, MacOS, Linux)";
     a065.style.direction = "rtl";
     a065.style.textAlign = "right";
    a066.innerHTML = "כפתורי מיקלדת:<br>";
    a066.innerHTML += "↑←↓→ ו '.ש.ד.ג: התחלת משחק.<br>";
    a066.innerHTML += "רווח: לעצור ולהמשיך את המשחק.<br>";
    a066.innerHTML += "ESC: פתיחת/סגירת התפריט.<br>";
    a066.innerHTML += "E: פתיחת/סגירת מרכז איסוף.<br>";
    a066.innerHTML += "Enter: המשך אם ההתראה פתוחה וסגירת חלון 'המשחק נגמר'.";
     a066.style.direction = "rtl";
     a066.style.textAlign = "right";
    a067.innerHTML = "כרטיס פרימיום";
    a068.innerHTML = "אסימון וירטואלי";
    a069.value = "העלאה(.js)";
     a069.style.direction = "rtl";
    a070.value = "טעינה";
    a071.innerHTML = "צבע הנחש";
    a072.innerHTML = "בקר קלאסי";
    a073.innerHTML = "בקר דינמי";
    a074.innerHTML = "מחוות מסך מגע";
    a075.innerHTML = "שרותים";
    a076.innerHTML = "הצג FPS (בטא)";
     a076.style.direction = "rtl";
    a077.innerHTML = "תנוחת נחש אופקית";
    a078.innerHTML = "תנוחת נחש אנכית";
    for (let i = 0; i < a000_all.length; i++) {
      a000_all[i].textContent = 'הגדרות:';
      a000_all[i].style.direction = "rtl";
      a000_all[i].style.textAlign = "right";
    };
    for (let i = 0; i < a001_all.length; i++) {
      a001_all[i].textContent = 'עיצוב:';
      a001_all[i].style.direction = "rtl";
      a001_all[i].style.textAlign = "right";
    };
    for (let i = 0; i < a002_all.length; i++) {
      a002_all[i].textContent = 'בקרוב!, חכו לעדכונים.';
      a002_all[i].style.direction = "rtl";
      a002_all[i].style.textAlign = "right";
    };
    for (let i = 0; i < a003_all.length; i++) {
      a003_all[i].textContent = 'עוד:';
      a003_all[i].style.direction = "rtl";
      a003_all[i].style.textAlign = "right";
    };
    for (let i = 0; i < a004_all.length; i++) {
      a004_all[i].textContent = 'להתחלה';
    };
    for (let i = 0; i < a005_all.length; i++) {
      a005_all[i].textContent = 'שירותים:';
      a005_all[i].style.direction = "rtl";
    };
    for (let i = 0; i < a006_all.length; i++) {
      a006_all[i].classList.add("he");
    };
    for (let i = 0; i < a007_all.length; i++) {
      a007_all[i].classList.add("he");
    };
//    for (let i = 0; i < a008_all.length; i++) {
//      a008_all[i].style.display = "flex";
//      a008_all[i].style.justifyContent = "space-between";
//    };
    for (let i = 0; i < a009_all.length; i++) {
      a009_all[i].style.textAlign = "right";
    };
    for (let i = 0; i < a010_all.length; i++) {
      a010_all[i].textContent = 'הורדה';
    };
    for (let i = 0; i < a011_all.length; i++) {
      a011_all[i].textContent = 'אנימה';
    };
    document.title = "מכה נחש אספן";
    document.getElementById("loadingFooter").style.direction = "rtl";
  }
}