let loadedcont = 0;
let errorscont = 0;
let widthcont = 0;
const widths = 100;
const basePaths = {
  boards: "index_data/textures/boards/",
  foods: "index_data/textures/foods/",
  guis: "index_data/textures/gui/",
  leagues: "index_data/textures/league/",
  snakes: "index_data/textures/snake/",
  systems: "index_data/textures/system/",
  loadingLogos: "index_data/animations/",
  cursorsClickable: "index_data/animations/cursour/clickable/",
  cursorsDelault: "index_data/animations/cursour/delault/",
  cursorsDisabled: "index_data/animations/cursour/disabled/",
  cursorsLeft: "index_data/animations/cursour/left/",
  cursorsRight: "index_data/animations/cursour/right/",
  cursorsUp: "index_data/animations/cursour/up/",
  cursorsDown: "index_data/animations/cursour/down/",
  others: "index_data/textures/",
  cardsMechas: "index_data/textures/images/cards/def_mecha/",
  cardsPilots: "index_data/textures/images/cards/def_pilot/",
  imagesMechas: "index_data/textures/images/views/def_mecha/",
  imagesPilots: "index_data/textures/images/views/def_pilot/",
  iconsMechas: "index_data/textures/images/icons/def_mecha/",
  iconsPilots: "index_data/textures/images/icons/def_pilot/",
  gachas: "index_data/textures/gui/gacha/",
  inventorys: "index_data/textures/gui/inventory/",
  gachaAnimations: "index_data/animations/gacha/",
  loadScreens: "index_data/textures/loading_screens/"
};
const assets = {
  boards: [
    "alpha_map",
    "alpha_map_2",
    "origo_map",
    "img_000",
    "img_001",
    "img_002",
    "img_003",
    "img_004",
    "img_005",
    "img_006",
    "img_007",
    "img_008",
    "img_009",
    "img_010",
    "img_011",
    "img_012",
    "img_013",
    "img_014",
    "img_015",
    "img_016",
    "img_017",
    "img_018",
    "img_019",
    "img_020",
    "img_021",
    "img_022",
    "img_023",
    "img_024",
    "img_025",
    "img_026",
    "img_027",
    "img_028",
    "img_029",
    "img_030",
    "img_031",
    "img_032",
    "img_033",
    "img_034",
    "img_035",
    "img_036",
    "img_037",
    "img_038",
    "img_039",
    "img_040",
    "img_041",
    "img_042",
    "img_043",
    "img_044",
    "img_045",
    "img_046",
    "img_047",
    "img_048",
    "img_049",
    "img_050",
    "img_051",
    "img_052",
    "img_053",
    "img_054",
    "img_055",
    "img_056",
    "img_057",
    "img_058",
    "img_059",
    "img_060",
    "img_061",
    "img_062",
    "img_063",
    "img_064",
    "img_065",
    "img_066",
    "img_067",
    "img_068",
    "img_069",
    "img_070",
    "img_071",
    "img_072"
  ],
  foods: [
    "alpha_coin",
    "crystal",
    "gold",
    "meaw_token",
    "ticket",
    "ticket_chromatic",
    "ticket_premium",
    "ticket_premium_2",
    "virtual_token",
    "img_0_000",
    "img_0_001",
    "img_0_002",
    "img_0_003",
    "img_0_004",
    "img_0_005",
    "img_0_006",
    "img_0_007",
    "img_0_008",
    "img_0_009",
    "img_0_010",
    "img_0_011",
    "img_0_012",
    "img_0_013",
    "img_0_014",
    "img_0_015",
    "img_0_016",
    "img_0_017",
    "img_0_018",
    "img_0_019",
    "img_0_020",
    "img_0_021",
    "img_0_022",
    "img_0_023",
    "img_0_024",
    "img_0_025",
    "img_0_026",
    "img_0_027",
    "img_0_028",
    "img_0_029",
    "img_0_030",
    "img_0_031",
    "img_0_032",
    "img_0_033",
    "img_0_034",
    "img_0_035",
    "img_0_036",
    "img_0_037",
    "img_0_038",
    "img_0_039",
    "img_0_040",
    "img_0_041",
    "img_0_042",
    "img_0_043",
    "img_0_044",
    "img_0_045",
    "img_0_046",
    "img_0_047",
    "img_0_048",
    "img_0_049",
    "img_0_050",
    "img_0_051",
    "img_0_052",
    "img_0_053",
    "img_0_054",
    "img_0_055",
    "img_0_056",
    "img_0_057",
    "img_0_058",
    "img_0_059",
    "img_0_060",
    "img_0_061",
    "img_0_062",
    "img_0_063",
    "img_0_064",
    "img_0_065",
    "img_0_066",
    "img_0_067",
    "img_0_068",
    "img_0_069",
    "img_0_070",
    "img_0_071",
    "img_0_072",
    "img_0_073",
    "img_0_074",
    "img_0_075",
    "img_0_076",
    "img_0_077"
  ],
  guis: [
    "actived_frame_cube",
    "alert",
    "bg_inner",
    "bg_overlay",
    "border",
    "btn_control_dn",
    "btn_control_dn_hover",
    "btn_control_lt",
    "btn_control_lt_hover",
    "btn_control_rt",
    "btn_control_rt_hover",
    "btn_control_up",
    "btn_control_up_hover",
    "btn_function_pe",
    "btn_function_py",
    "button",
    "button_true",
    "cards_continer",
    "changed_bg",
    "checkbox_off",
    "checkbox_on",
    "close",
    "collection_bg",
    "cube_bg",
    "exit",
    "first_modal_bg",
    "floor",
    "hard_on",
    "hell_on",
    "htp_button",
    "icon_bg",
    "icon_mecha",
    "icon_pilot",
    "icon_shop",
    "key_bg",
    "key_bg_hover",
    "line",
    "list_bg",
    "loading_progress",
    "loading_yi_logo_2x",
    "logo",
    "long_button",
    "long_button_hover",
    "menu",
    "menu_close",
    "mini_modal",
    "mini_modal_close",
    "minus_cube",
    "nav_menu",
    "normal_on",
    "notice",
    "opx1",
    "opx10",
    "plus_cube",
    "range_bar",
    "range_thumb",
    "selected",
    "services_bg",
    "shop_item",
    "shop_item_detiles",
    "shop_item_obtained",
    "shop_tab_vertical",
    "shop_window",
    "skip",
    "tab_horizontal",
    "tab_off",
    "tab_vertical",
    "tab_vertical_ltr",
    "tabs_continer",
    "unselected",
    "up_note",
    "what_it_do",
    "windows_bg",
    "wrapper_bg"
  ],
  leagues: [
    "league_1_bronze",
    "league_2_silver",
    "league_3_gold",
    "league_4_platinum",
    "league_5_diamond",
    "league_6_super",
    "league_7_legendary",
    "league_8_alpha_knight",
    "non",
    "league_1_bronze_star",
    "league_2_silver_star",
    "league_3_gold_star",
    "league_4_platinum_star",
    "league_5_diamond_star",
    "league_6_super_star",
    "league_7_legendary_star",
    "league_8_alpha_knight_star",
    "non_star"
  ],
  snakes: [
    "0",
    "0s",
    "1",
    "1s",
    "2",
    "2s",
    "3",
    "3s",
    "4",
    "4s",
    "5",
    "5s",
    "6",
    "6s",
    "7",
    "7s",
    "8",
    "8s",
    "9",
    "9s",
    "a",
    "As",
    "b",
    "Bs",
    "c",
    "Cs",
    "d",
    "Ds",
    "e",
    "Es",
    "f",
    "Fs",
    "g",
    "Gs",
    "h",
    "Hs",
    "i",
    "Is",
    "j",
    "Js",
    "k",
    "Ks",
    "l",
    "Ls",
    "m",
    "Ms",
    "n",
    "Ns",
    "o",
    "Os",
    "p",
    "Ps",
    "q",
    "Qs",
    "r",
    "Rs",
    "s",
    "Ss",
    "t",
    "Ts",
    "u",
    "Us",
    "v",
    "Vs",
    "w",
    "Ws",
    "x",
    "Xs",
    "y",
    "Ys",
    "z",
    "Zs"
  ],
  systems: [
    "battery_charging",
    "battery_low",
    "battery_normal",
    "battery_main_charging",
    "battery_main_low",
    "battery_main_normal",
    "icon_0",
    "icon_16",
    "icon_32",
    "icon_48",
    "icon_76",
    "icon_96",
    "icon_120",
    "icon_128",
    "icon_144",
    "icon_152",
    "icon_167",
    "icon_180",
    "icon_192",
    "icon_196",
    "icon_228",
    "icon_256",
    "icon_300",
    "icon_384",
    "icon_512",
    "discord"
  ],
  loadingLogos: [
    "anime",
    "classic",
    "miku",
    "nakano_azusa",
    "anime_2",
    "anime_3"
  ],
  cursorsClickable: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15"
  ],
  cursorsDelault: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15"
  ],
  cursorsDisabled: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15"
  ],
  cursorsLeft: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13"
  ],
  cursorsRight: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13"
  ],
  cursorsUp: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13"
  ],
  cursorsDown: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13"
  ],
  others: [
    "empty"
  ],
  cardsMechas: [
    "Akashic",
    "Alborada",
    "Andromeda",
    "Arthur",
    "Aurora",
    "Boltus",
    "Caramel",
    "Death Knell",
    "Doomlight",
    "Dreadwolf",
    "Firefox",
    "Firestar",
    "Flamenco",
    "Gabriel",
    "Gaia",
    "Guerilla Hunter",
    "Hotsteel",
    "Hurricane",
    "Jojo",
    "Lancelot",
    "Michael",
    "Moon Rabbit",
    "Nebula",
    "Neutron Star",
    "Northern Knight",
    "Pulsar",
    "Ranger",
    "Raven",
    "Shiranui",
    "Skyfall",
    "Skyfire",
    "Skylark",
    "Snow Mirage",
    "Tempest",
    "Trio of Enders",
    "Twilight",
    "Ventorus"
  ],
  imagesMechas: [
    "Akashic",
    "Alborada",
    "Andromeda",
    "Arthur",
    "Aurora",
    "Boltus",
    "Caramel",
    "Death Knell",
    "Doomlight",
    "Dreadwolf",
    "Firefox",
    "Firestar",
    "Flamenco",
    "Gabriel",
    "Gaia",
    "Guerilla Hunter",
    "Hotsteel",
    "Hurricane",
    "Jojo",
    "Lancelot",
    "Michael",
    "Moon Rabbit",
    "Nebula",
    "Neutron Star",
    "Northern Knight",
    "Pulsar",
    "Ranger",
    "Raven",
    "Shiranui",
    "Skyfall",
    "Skyfire",
    "Skylark",
    "Snow Mirage",
    "Tempest",
    "Trio of Enders",
    "Twilight",
    "Ventorus"
  ],
  iconsMechas: [
    "Akashic",
    "Alborada",
    "Andromeda",
    "Arthur",
    "Aurora",
    "Boltus",
    "Caramel",
    "Death Knell",
    "Doomlight",
    "Dreadwolf",
    "Firefox",
    "Firestar",
    "Flamenco",
    "Gabriel",
    "Gaia",
    "Guerilla Hunter",
    "Hotsteel",
    "Hurricane",
    "Jojo",
    "Lancelot",
    "Michael",
    "Moon Rabbit",
    "Nebula",
    "Neutron Star",
    "Northern Knight",
    "Pulsar",
    "Ranger",
    "Raven",
    "Shiranui",
    "Skyfall",
    "Skyfire",
    "Skylark",
    "Snow Mirage",
    "Tempest",
    "Trio of Enders",
    "Twilight",
    "Ventorus"
  ],
  cardsPilots: [
    "Aya",
    "Belladonna",
    "Cyrus",
    "Fran",
    "Furanku",
    "Iori",
    "Ivan",
    "Jaka",
    "Jiu Chong",
    "Joanna",
    "Kije",
    "Kikina",
    "Kizuna Ai",
    "Lillian",
    "Lysa",
    "Matilda",
    "Mia",
    "Mila",
    "Mobius",
    "Nighthawk",
    "Ning",
    "Norma",
    "Opal",
    "Purity",
    "RED",
    "Riko",
    "Rom",
    "Serena",
    "Shin",
    "Silver Deacon",
    "Tarantula",
    "Vanessa",
    "Villar",
    "Vita",
    "Yang",
    "Yulia",
    "Yutong",
    "Zoe"
  ],
  imagesPilots: [
    "Aya",
    "Belladonna",
    "Cyrus",
    "Fran",
    "Furanku",
    "Iori",
    "Ivan",
    "Jaka",
    "Jiu Chong",
    "Joanna",
    "Kije",
    "Kikina",
    "Kizuna Ai",
    "Lillian",
    "Lysa",
    "Matilda",
    "Mia",
    "Mila",
    "Mobius",
    "Nighthawk",
    "Ning",
    "Norma",
    "Opal",
    "Purity",
    "RED",
    "Riko",
    "Rom",
    "Serena",
    "Shin",
    "Silver Deacon",
    "Tarantula",
    "Vanessa",
    "Villar",
    "Vita",
    "Yang",
    "Yulia",
    "Yutong",
    "Zoe"
  ],
  iconsPilots: [
    "Aya",
    "Belladonna",
    "Cyrus",
    "Fran",
    "Furanku",
    "Iori",
    "Ivan",
    "Jaka",
    "Jiu Chong",
    "Joanna",
    "Kije",
    "Kikina",
    "Kizuna Ai",
    "Lillian",
    "Lysa",
    "Matilda",
    "Mia",
    "Mila",
    "Mobius",
    "Nighthawk",
    "Ning",
    "Norma",
    "Opal",
    "Purity",
    "RED",
    "Riko",
    "Rom",
    "Serena",
    "Shin",
    "Silver Deacon",
    "Tarantula",
    "Vanessa",
    "Villar",
    "Vita",
    "Yang",
    "Yulia",
    "Yutong",
    "Zoe"
  ],
  gachas: [
    "1d",
    "2c",
    "3b",
    "4a",
    "5s",
    "6sp",
    "7ss"
  ],
  inventorys: [
    "item_bg_1d",
    "item_bg_2c",
    "item_bg_3b",
    "item_bg_4a",
    "item_bg_5s",
    "item_bg_6sp",
    "item_bg_7ss",
    "item_ic_1d",
    "item_ic_2b",
    "item_ic_4s",
    "item_ic_5sp",
    "item_ic_6ex",
    "item_ic_6sp",
    "item_ic_6ss",
    "lock"
  ],
  gachaAnimations: [
    "gacha_vid_press",
    "gacha_vid_pressed_0d",
    "gacha_vid_pressed_1c",
    "gacha_vid_pressed_2b",
    "gacha_vid_pressed_3a",
    "gacha_vid_pressed_4s",
    "gacha_vid_pressed_5sp",
    "gacha_vid_pressed_6ss",
    "gacha_vid_start"
  ],
  loadScreens: [
    "0"
  ]
};
const extensions = {
  boards: [".png"],
  foods: [".png"],
  guis: [".png"],
  leagues: [".png"],
  snakes: [".png"],
  systems: [".png"],
  cursorsClickable: [".png"],
  cursorsDelault: [".png"],
  cursorsDisabled: [".png"],
  cursorsLeft: [".png"],
  cursorsRight: [".png"],
  cursorsUp: [".png"],
  cursorsDown: [".png"],
  others: [".png"],
  cardsMechas: [".png"],
  cardsPilots: [".png"],
  imagesMechas: [".png"],
  imagesPilots: [".png"],
  iconsMechas: [".png"],
  iconsPilots: [".png"],
  gachas: [".png"],
  inventorys: [".png"],
  loadScreens: [".png"],
  loadingLogos: [".gif"],
  gachaAnimations: [".gif"]
};
const maxAssets = Object.values(assets).reduce((a, arr) => a + arr.length, 0);
function loadTextures() {
  const loadedBar = document.getElementById("loadedbar");
  if (!loadedBar) return console.error("Missing element: loadedbar");
  for (const [folder, list] of Object.entries(assets)) {
    const base = basePaths[folder];
    const exts = extensions[folder] || extensions.default;
    if (!base) {
      console.warn(`⚠️ Missing base path for folder: ${folder}`);
      continue;
    }
    for (const name of list) {
      const img = document.createElement("img");
      img.style.cssText = "width:1px;height:1px;opacity:0;";
      img.dataset.folder = folder;
      img.dataset.name = name;
      img.dataset.extIndex = 0;
      img.src = base + name + exts[0];
      img.addEventListener("load", handleLoad);
      img.addEventListener("error", () => handleImageError(img, base, name, exts));
      loadedBar.appendChild(img);
    }
  }
};
function handleImageError(img, base, name, exts) {
  const currentIndex = parseInt(img.dataset.extIndex, 10);
  if (currentIndex + 1 < exts.length) {
    img.dataset.extIndex = currentIndex + 1;
    img.src = base + name + exts[currentIndex + 1];
  } else {
    handleError();
  }
};
function handleLoad() {
  loadedcont++;
  widthcont = (loadedcont / maxAssets) * 100;
  const widther = document.getElementById("widther");
  if (widther) widther.style.width = widthcont + "%";
  document.getElementById("assetCount").innerHTML = `${loadedcont}/${maxAssets}`;
  document.getElementById("widthernum").innerHTML = `${widthcont.toFixed(1)}% / ${widths}%`;
  if (loadedcont === maxAssets) toDisplayNone();
};
function handleError() {
  errorscont++;
  const lang = localStorage.getItem("lang");
  const el = document.getElementById("loadingText");
  if (!el) return;
  const messages = {
    en: `Cant load ${errorscont} assets, not found or removed...<br>maybe try reload, if again not loaded tell us.`,
    ru: `Невозможно загрузить ${errorscont} активов, они не найдены или удалены...<br>попробуйте перезагрузить, если снова не загрузится, сообщите нам.`,
    he: `לא ניתן לטעון ${errorscont} נכסים, לא נמצאו או הוסרו...<br>אולי תנסה לטעון מחדש, אם שוב לא נטען הודיעו לנו.`
  };
  el.innerHTML = messages[lang] || messages.en;
  document.getElementById("loadingService").style.display = "flex";
};
function toDisplayNone() {
  document.getElementById("loading").style.display = "none";
  const firstModal = localStorage.getItem("firstModal");
  if (firstModal === null || firstModal === "") {
    document.getElementById("firstModal").style.display = "block";
  } else {
    alertAccept();
  }
};
function toDisplayNone() {
  document.getElementById("loading").style.display = "none";
  const firstModal = localStorage.getItem("firstModal");
  if (firstModal === null || firstModal === "") {
    document.getElementById("firstModal").style.display = "block";
  } else {
    alertAccept();
  }
}