const cosmicechos = [
  { name: "Aya", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Aya.png" },
  { name: "Belladonna", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Belladonna.png" },
  { name: "Cyrus", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Cyrus.png" },
  { name: "Fran", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Fran.png" },
  { name: "Furanku", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Furanku.png" },
  { name: "Iori", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Iori.png" },
  { name: "Ivan", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Ivan.png" },
  { name: "Jaka", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Jaka.png" },
  { name: "Jiu Chong", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Jiu Chong.png" },
  { name: "Joanna", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Joanna.png" },
  { name: "Kije", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Kije.png" },
  { name: "Kikina", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Kikina.png" },
  { name: "Matilda", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Matilda.png" },
  { name: "Lillian", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Lillian.png" },
  { name: "Lysa", rarity: "Default", image: "index_data/textures/images/cards/def_pilot/Lysa.png" },
  { name: "Hurricane", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Hurricane.png" },
  { name: "JOJO", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Jojo.png" },
  { name: "Lancelot", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Lancelot.png" },
  { name: "Michael", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Michael.png" },
  { name: "Moon Rabbit", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Moon Rabbit.png" },
  { name: "Nebula", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Nebula.png" },
  { name: "Neutron Star", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Neutron Star.png" },
  { name: "Northern Knight", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Northern Knight.png" },
  { name: "Pulsar", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Pulsar.png" },
  { name: "Ranger", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Ranger.png" },
  { name: "Raven", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Raven.png" },
  { name: "Shiranui", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Shiranui.png" },
  { name: "Skyfall", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Skyfall.png" },
  { name: "Skyfire", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Skyfire.png" },
  { name: "Skylark", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Skylark.png" },
  { name: "Snow Mirage", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Snow Mirage.png" },
  { name: "Tempest", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Tempest.png" },
  { name: "Trio of Enders", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Trio of Enders.png" },
  { name: "Twilight", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Twilight.png" },
  { name: "Ventorus", rarity: "Default", image: "index_data/textures/images/cards/def_mecha/Ventorus.png" },
  { name: "Cosmic Pulse", rarity: "Srank", image: "index_data/gacha_events/cosmic_echo/card_cosmic_pulse_1.png" },
  { name: "Dj Hacker", rarity: "Srank", image: "index_data/gacha_events/cosmic_echo/card_dj_hacker_1.png" }
];